### ISSUE TITLE
WooCommerce 9.5 has a similar feature: Convert guest shoppers to logged in buyers

### ISSUE THREAD

**Issue by greguly** [s-azizkhan/create-user-from-guest-order-wp-plugin#5]
[Convert guest shoppers to logged in buyers](https://developer.woocommerce.com/2024/12/17/woocommerce-9-5-convert-guests-to-loyal-customers-through-delayed-account-creation-and-cross-selling/#h-convert-guest-shoppers-to-logged-in-buyers)

**Comment by s-azizkhan** [comment]
This feature is great, as per the [feature](https://developer.woocommerce.com/2024/12/17/woocommerce-9-5-convert-guests-to-loyal-customers-through-delayed-account-creation-and-cross-selling/#h-convert-guest-shoppers-to-logged-in-buyers:~:text=The%20new%20delayed%20account%20creation%20feature%20adds%20a%20%E2%80%9CCreate%20Account%E2%80%9D%20block%20to%20the%20order%20confirmation%20page.) `The new delayed account creation feature adds a “Create Account” block to the order confirmation page` so that means this will not create account automatically, feature is for manual account creation after checkout
